### ISSUE TITLE
Changing from HTTP to HTTPS

### ISSUE THREAD

**Issue by AashaiAvadhani1** [AashaiAvadhani1/FLP-Inventory#11]

**Comment by TomasVCMU** [comment]
See commits in PR: 1c57ef61eac81841159c5cdf981c277435fff871.

These add Caddy as the reverse proxy to be able to communicate with LetsEncrypt for the SSL certificate.

![Screen Shot 2022-04-20 at 1 31 56 PM](https://user-images.githubusercontent.com/72578647/164289120-5c2bc70a-96e2-405c-86ec-696834e4696a.png)
