### ISSUE TITLE
Adding New Item

### ISSUE THREAD

**Issue by AashaiAvadhani1** [AashaiAvadhani1/FLP-Inventory#13]
Description: Adding the items to the database and not using the category "used" and only using the ones that we need such as the "size" and "name of clothing"

**Comment by SantianLin** [comment]
branch "outdated_added" now adds a new column named "outdated". This field would have a default value to help distinguish outdated items with newly added items. 
Note that Migration has been run and a script is used to change database.
TODO: think about what items need to be added. (What items/categories need to remain) And which outdated items are included in them.
