### ISSUE TITLE
Update instructions for deploying

### ISSUE THREAD

**Issue by AashaiAvadhani1** [AashaiAvadhani1/FLP-Inventory#26]

**Comment by TomasVCMU** [comment]
See commit a994bc09c939aed7c2021902e14cd714281f2a0b, a994bc09c939aed7c2021902e14cd714281f2a0b, and 3ee0a8431cb8f0914d6a7f9bbb5e7bdc45c57b37. 

These commits add updated deployment instructions with further clarity on the old team's instructions and update it to the new process - adding files and using docker-compose.
