### ISSUE TITLE
 SSL Migrating to Cloudfare

### ISSUE THREAD

**Issue by AashaiAvadhani1** [AashaiAvadhani1/FLP-Inventory#28]
We need to migrate the DNS to CloudFlare to be able to use Caddy as a reverse proxy for an SSL certificate with LetsEncrypt.

**Comment by TomasVCMU** [comment]
See CloudFlare's website and log in with the user and password noted in Google Drive Sensitive Details document. DNS is now handled through CloudFlare by having custom nameservers on Namecheap (domain registrar) and subsequently adding the DNS records to CloudFlare.
