### ISSUE TITLE
Recommended Items (Quick Adds)

### ISSUE THREAD

**Issue by AashaiAvadhani1** [AashaiAvadhani1/FLP-Inventory#4]
Description: Have a panel to the right of the search bar that contains the most popular items that sell for a quicker process throughout the checkout panel

Frontend

- [ ] Displaying images/icon
- [ ] Adding a text layer below images as a caption
- [ ] Below the picture have a button that says: "Add to cart"

Backend

- [ ] create recommended section that has top 5 most popular sold items with icons
- [ ] edit search feature on checkout/checkin page so that most popular items (ie. teen pants used) pop up first within search bar
- [ ] Store the top 5 selling items (shoes, pants, shirts etc...)

Time Estimation: 10 hours

Notes from professors - this card feels like epic. Explicitly turn the checkbox tasks into separate cards. Possibly turn the tasks into separate cards.

**Comment by hkhang1883** [comment]
- the related branch is called 'rec_item' however we are not ready to create a pull request yet due to roadblocks so we cannot link the branch to this issue yet
