### ISSUE TITLE
Search Bar Code System

### ISSUE THREAD

**Issue by AashaiAvadhani1** [AashaiAvadhani1/FLP-Inventory#7]
Description: Have a system that detects smaller keyphrases (acronyms) that map to the items related on the search bar. For example, BP for baby pants. Focuses on improving the search aspect of all the categories. Edited for the check-in and the check-out process.

**Front-End**

- [ ] No changes to the display of the search bar

**Back-End**

- [ ] A data structure (dictionary) to map keywords to items

Estimated Time: 4 hours

**Comment by TomasVCMU** [comment]
We decided to fix this with Recommended Items instead - closing this issue.
